services:
  shellcoder:
    image: cybersecnatlab/challenge-jail@sha256:a90fb2f6c9b460b8ed559bf78d5cbd084bff11fda5feb863229ec51d58641871
    restart: unless-stopped
    init: true
    privileged: true
    volumes:
      - './build/shellcoder:/home/user/chall:ro'
    ports:
      - '1337:1337'
    environment:
      - 'FLAG=CCIT{fake_flag}'
      - 'TIMEOUT=30'
